### ISSUE TITLE
Issues with redstone

### ISSUE THREAD

**Issue by imagelesskink** [Tschipcraft/dynamiclights#12]
### Describe the bug

Placing the light block causes block updates, triggering BUDs. This also causes cave-ins. Also, the light block isn't pushable, so players are completely unable to be pushed by pistons at feet level, making all slime elevators and bounce pads inoperable. Can you make it so the light block placement suppresses updates and light blocks are pushable?

### Steps to reproduce

1. Hold a torch
2. Walk in front of an observer

1. Hold a torch
2. Step on top of an upwards-facing piston
3. Power the piston

### Expected behavior

Observers and BUDs are not triggered and players can be pushed by pistons

**Comment by Tschipcraft** [comment]
Thank you for the bug report.
I never thought the light block wouldn't be pushable smh

I sadly can't make the block pushable and prevent block updates with my current approach (just no way to do it with data packs), but I can add a system that tries to avoid placing light blocks in problematic areas.

**Comment by Tschipcraft** [comment]
This should be fixed in v1.8 🎉
If you are still experiencing problems, feel free to reopen this issue.
