### ISSUE TITLE
Datapack breaks tnt duping

### ISSUE THREAD

**Issue by Summa2Blasphemia** [Tschipcraft/dynamiclights#15]
### Describe the bug

After installing this datapack I went to use my treefarm, design by ianxofour. The tnt duper at the top of the machine destroyed itself which it never did before. I copied dupers from the wiki as well as a youtube video, still broken. 

### Steps to reproduce

1. Construct these 3 dupers: 

https://minecraft.wiki/w/Tutorials/Block_and_item_duplication#Piston-based_TNT_Duplication

https://www.youtube.com/watch?v=6xe4I4EqnFw&list=PLLXaW6y5zOxwDRSaTOZfIXm4myEZHhp_B&index=26&t=595s&ab_channel=ianxofour

https://www.youtube.com/watch?v=_MOFl0MmuEE&ab_channel=Kale

or use these schematics: https://www.dropbox.com/scl/fo/8pn0q6zszzsl5budlvdy7/h?rlkey=31qdp4jsa2ary1y2lqux8is65&dl=0

### Expected behavior

Dupers should duplicate the tnt and let it drop. One tnt should stay with the machine to be duped again. The duped tnt at the top of the tree farm should fall and when the machine is turned off should explode at the top in the waterlogged slab without destroying the surrounding blocks.

**Comment by Tschipcraft** [comment]
Thanks for clarifying, looks like the fix for #10 wasn't enough...
This will be fixed in a future release!

**Comment by Tschipcraft** [comment]
This should be fixed in v1.8 🎉
If you are still experiencing problems, feel free to reopen this issue.
