### ISSUE TITLE
Incompatible with Moving Elevators mod by SuperMartijn642

### ISSUE THREAD

**Issue by YoshiNoodles** [Tschipcraft/dynamiclights#17]
### Is your feature request related to a problem? Please describe.

I'm playing a friend's server with this mod enabled and I've noticed a few issues it causes with some other mods due to the nature of the generated light block.  Firstly, the elevators we make with the Moving Elevators mod don't move if you're standing in them wearing enchanted armor and/or holding something that generates light; and secondly, we have the Macaw's Lights and Lamps mod and those lights get switched off if you're too close to them wearing/holding a light-generating item due to a bug with that mod.

### Describe the feature you'd like

Ideally, there would be a config file wherein you could disable the dynamic lighting effects of certain blocks/items whilst keeping others intact -- for example, disabling the dynamic lighting effects of enchanted tools/items whilst leaving the effects for light-generating blocks active.

### Describe alternatives you've considered

Note that Macaw will be fixing the bug in his mod to eliminate that issue; however, removing the issues with Moving Elevators has to happen via Dynamic Lighting, ideally via the aforementioned config file.

### Additional context

MC 1.19.2
Forge 43.3.0

_No response_

**Comment by YoshiNoodles** [comment]
The fix doesn't seem to have worked.  The thing is that the Moving Elevators controller counts every block in the car as part of the car, air included, so the light blocks would be part of the car as well, and because they can't be pushed by pistons, the elevator can't move.

**Comment by Tschipcraft** [comment]
That's a shame, I'm unsure if I will be able to fix this then. The only option I see would be editing the code of the light block to make it pushable in the mod version. I'll leave this issue open until I have figured something out.

**Comment by Tschipcraft** [comment]
This issue has been fixed as of Moving Elevators v1.4.6 🎉
