### ISSUE TITLE
Unnamed markers apear where the dyanmic lights apear.

### ISSUE THREAD

**Issue by Benji7010** [Tschipcraft/dynamiclights#19]
### Describe the bug

Whenever I or a mob I encountered has dynamic lights, unnamed markers appear where the light comes from.
![2024-01-26_22 13 26_4K](https://github.com/Tschipcraft/dynamiclights/assets/82925364/6a8b9801-c775-4c2d-8440-0238f9319f5a)

### Steps to reproduce

1. Install Axiom with dynamic lights.
2. Play a world in creative mode.
3. Hold out a dynamic light source or find something that produces dynamic lights.

**Comment by Tschipcraft** [comment]
This is just how this project works at its core. It saves the positions of dynamic lights for the next tick using the mentioned marker entities. Normally, marker entities are not even sent to the client, so there would be no way for players to see them, but the mod you are playing with makes them visible.
I could maybe give the markers a name, but other than that, I'm not sure if I can change anything about this.

**Comment by Tschipcraft** [comment]
As of v1.8, all markers get a custom name including light level information.  
Since using markers is how this project works and switching to a different method for storing dynamic light positions is currently not in development, I will close this issue as not planned for now.
