### ISSUE TITLE
Add Totem of Undying

### ISSUE THREAD

**Issue by WarLord211** [Tschipcraft/dynamiclights#23]
### Is your suggested enhancement related to a problem? Please describe.

Add the totem of undying to the Light emiting items.

### Describe the solution you'd like

"minecraft:totem_of_undying",  in 6.json

### Describe alternatives you've considered

better in 3 when available

### Additional context

Thx for your work on the pack. We love it!

**Comment by Tschipcraft** [comment]
Thank you for the suggestion!
