### ISSUE TITLE
Setting to turn off torch glow.

### ISSUE THREAD

**Issue by BleuFaux** [Tschipcraft/dynamiclights#26]
### Is your suggested enhancement related to a problem? Please describe.

The current implementation of the hand-held torch lighting flickers as you walk. It's subtle but is bothersome, I realize this may not be fixable, but my shader already does the same thing without the flicker, so I would like to be able to turn this specific feature off. 

### Describe the solution you'd like

I would like a setting in the config file/menu to be able to specifically turn the hand-held torch lighting feature on and off.

**Comment by Tschipcraft** [comment]
Thank you for the suggestion. Does this only specifically apply to holding a torch or other items/other locations like a torch item as well?

**Comment by BleuFaux** [comment]
Hmm, so in the case of the shader, it seems to only work on the torch and the lantern. So for my personal use it would only need to be those two BUT, that may not be the case for all shaders. I guess one option is to turn it off for anything being held by the player. Or maybe just the two major items, torches and lanterns, but allow it for items you have added light too? I think 99% of the time the issue will be related to just torches held by the player though.

**Comment by Tschipcraft** [comment]
Alright, I'll see what I can do
