### ISSUE TITLE
Add 1.20.5/6 Support

### ISSUE THREAD

**Issue by BrailleBennett** [Tschipcraft/dynamiclights#27]
Add support for 1.20.5/6, as it is currently missing.

**Comment by Tschipcraft** [comment]
Support for 1.20.5/1.20.6 is in the works. 
As there have been some massive technical changes between 1.20.4 and 1.20.5, this may still take some time. To get a sense of the scope, [slicedlimes' video](https://www.youtube.com/watch?v=A2mphZA1Gho) covering all the technical changes is 53 minutes long...
Thanks for your patience.

**Comment by baldo3000** [comment]
> Support for 1.20.5/1.20.6 is in the works. As there have been some massive technical changes between 1.20.4 and 1.20.5, this may still take some time. To get a sense of the scope, [slicedlimes' video](https://www.youtube.com/watch?v=A2mphZA1Gho) covering all the technical changes is 53 minutes long... Thanks for your patience.

Is there a way to build dev builds by myself? I can't find the the build.gradle file so I don't know where to start

**Comment by Tschipcraft** [comment]
Yeah... my build process is a bit weird to be able to support this big of a version range. I basically redistribute the already built class files. You'll need to
1. Download the source code
2. Rename any occurrences of `${version}` with e.g. 1.8-beta (most importantly in the fabric.mod.json and/or mods.toml files) (and if you want, but not necessary for the mod version, `${file_name}` with the name of the built file excluding the extension and `${mc_version}` with the plaintext mc version range e.g. 1.17x-1.20x)
3. Zip everything from the root directory excluding .github, src, wiki and .gitattributes
4. Rename the extension of the zip file to .jar

This should give you a working mod version, I'm however currently testing the changes only on the data pack version, so don't be surprised if it doesn't work yet.

**Comment by baldo3000** [comment]
Thanks, it works!

**Comment by baldo3000** [comment]
The game opens correctly but every item in the hand emits light, not only glowing objects. I used it as a mod

**Comment by Tschipcraft** [comment]
Thanks for letting me know, I'll have a look at it

**Comment by Tschipcraft** [comment]
While testing the 1.20.6 mod version on Forge and Fabric, I did not experience this problem. Are you sure you built the mod using the dev branch code?
