### ISSUE TITLE
Incompatible with Minecraft 1.21

### ISSUE THREAD

**Issue by rock3tsprocket** [Tschipcraft/dynamiclights#29]
### Describe the bug

everything lights up

### Steps to reproduce

1: install the datapack in a world for 24w18a (idk if the mod also does that)
2: hold/drop anything

### Expected behavior

for only the stuff listed in the readme to light up

**Comment by Tschipcraft** [comment]
Thanks for the report. I will however first focus on compatibility for 1.20.5/1.20.6.

**Comment by Tschipcraft** [comment]
Well, the Java change isn't really that big of a deal, at least for this project. It's the new [item components](https://minecraft.wiki/w/Data_component_format) that make the pack incompatible.

**Comment by BrailleBennett** [comment]
Did fixing it for 1.20.6 automagically fix it for 1.21?

**Comment by Tschipcraft** [comment]
Well, it definitely helped, but some parts are for sure not compatible with the latest snapshot yet

**Comment by Tschipcraft** [comment]
Support for Snapshot 24w18a itself was added with this commit (forgot to link): https://github.com/Tschipcraft/dynamiclights/commit/2ea659d1ca2cd70eb016cf91dd77fd9cbc17a72d
Temporary dev builds for this commit are available [here](https://github.com/Tschipcraft/dynamiclights/actions/runs/9799017658).

Support for the next snapshots up to 1.21 is in the works.
