### ISSUE TITLE
error when accessing in Minecraft 1.20.1

### ISSUE THREAD

**Issue by millennIumAMbiguity** [Tschipcraft/dynamiclights#30]
### Describe the bug

![image](https://github.com/Tschipcraft/dynamiclights/assets/37588844/82e08eae-1886-482c-b068-f1e6ba974842)

### Steps to reproduce

1. run `/trigger tschipcraft.menu` in Minecraft 1.20.1
2. press [Settings]

**Comment by Tschipcraft** [comment]
To be able to change (or view) the settings, you need to have operator permissions. This was done so that the settings can't be changed by random players e.g. in public servers running Dynamic Lights.
