### ISSUE TITLE
Configurable light level.

### ISSUE THREAD

**Issue by millennIumAMbiguity** [Tschipcraft/dynamiclights#31]
### Is your feature request related to a problem? Please describe.

The light level is too high I think, I would like to be able to lower it.

**Comment by Tschipcraft** [comment]
If you have suggestions for specific changes, feel free to make an enhancement issue, otherwise follow the [steps in the wiki to change it yourself](https://github.com/Tschipcraft/dynamiclights/wiki/Edit-Supported-Items).
