### ISSUE TITLE
The pack isn't working on 1.20.6

### ISSUE THREAD

**Issue by BrailleBennett** [Tschipcraft/dynamiclights#34]
### Describe the bug

I have the datapack v1.8 installed on my purpur 1.20.6 server. It loaded successfully and there is no error, but when my player holds a torch, no dynamic light is cast. I'm not really sure how to trouble shoot better or provide more info, since as a datapack, there's no configuration, logging, or alternative way to install it. The pack shows up in /datapacks list

### Steps to reproduce

Join a purpur 1.20.6 server
Hold a torch
Suffer

### Expected behavior

A light block is placed while the torch is held

**Comment by Tschipcraft** [comment]
Thanks for letting me know, looks like the build script ignored the newly added overlays. A hotfix is on the way!

**Comment by Tschipcraft** [comment]
Oh damn, didn't work again...

**Comment by Tschipcraft** [comment]
v1.8.2 should work correctly on 1.20.6 now
