### ISSUE TITLE
Disabled lights per player?

### ISSUE THREAD

**Issue by Boba194230** [Tschipcraft/dynamiclights#37]
### Is your suggested enhancement related to a problem? Please describe.

So I'm a shader user and can run pretty decent shaders and like their implementation of dynamic lights but my friends don't run modded so they don't have shaders but I want them to have dynamic lights too but whenever I'm using this the shader dynamic lights and this are both working and causing some very odd lighting.

### Describe the solution you'd like

If there was someway for a client to maybe have the mod and disable some setting so that they don't see the dynamic lights that'd be great.

### Describe alternatives you've considered

I've thought about just removing the mod but I really do think it would be great for my friends to have dynamic lights so I want to try making it work. I also thought about disabling the dynamic lights from the shader but they're so smooth and colored nicely that I would like to keep that if possible.

**Comment by Tschipcraft** [comment]
Thanks for your suggestion. Please take a look [at my response to a previous issue](https://github.com/Tschipcraft/dynamiclights/issues/3#issuecomment-1450437262) regarding this, but I guess an option for players to specifically turn off light generation from themselves - at the cost of other players not seeing dynamic light from them as well - would be possible (and an easy fix for #26)

**Comment by Boba194230** [comment]
Sorry I didn’t fully read the other I had just browsed titles. Makes sense that it wouldn’t be viable to do I was just wondering, awesome job on everything though, the new update is amazing!

**Comment by Boba194230** [comment]
Also maybe it could be as simple as adding a blacklist to the config file on the server to disable it with player ids or whatever
