### ISSUE TITLE
Which permissions need to be enable to be able to use dynamic lights?

### ISSUE THREAD

**Issue by helpful-sam** [Tschipcraft/dynamiclights#40]
### Describe the bug

On my server (running luckperms), I have two groups: default and admin.

The Default group gets a blanket * permission to be false and the admin group gets a blanket * permission to be true.

When I am set to the admin group, dynamic light works as expected, but when I'm in the default group, dynamic light does not work as expected.

Looking at the permission nodes of dynamic lights, I see nodes for using/viewing the config commands, but not any that would be responsible for using dynamic lights... any ideas?

### Steps to reproduce

Make a group on luckperms to have all permissions false using the * wildcard node 

### Expected behavior

Dynamic lighting works without command permissions

### Additional context

running 1.20.6, with clients having manually chosen to run 1.20.6 instead of "latest version," as 1.21 has been released

**Comment by Tschipcraft** [comment]
Thank you for the bug report. There shouldn't be any permissions required for dynamic lights to appear around a player. I'm guessing luckperms also controls which players are detected with predicates or selectors? I'll have to look into that.

**Comment by helpful-sam** [comment]
SOLVED: I forgot to mention the fact that I also use universal perms alongside luckperms, and it turns out there is a node called "universal_perms.misc.selector" which, if set to false, dynamic lights will not work for players!

**Comment by Tschipcraft** [comment]
Thanks for letting me know, I'll add this info to the wiki in the future
