### ISSUE TITLE
1.21 when

### ISSUE THREAD

**Issue by Legendmanj** [Tschipcraft/dynamiclights#44]
### Is your feature request related to a problem? Please describe.

problem of mod to be updated

### Describe the feature you'd like

implementation of 1.21 version

### Describe alternatives you've considered

this is and will be ig (;

### Additional context

asap please! thankyou

**Comment by Tschipcraft** [comment]
As stated in all the other issues regarding this, I will start working on the update in approx. 1 week after my final exams. Please be patient.

**Comment by Tschipcraft** [comment]
Duplicate of #29
