### ISSUE TITLE
In 1.20 pre1 / RC1 no light emiting from Hand/Armour

### ISSUE THREAD

**Issue by WarLord211** [Tschipcraft/dynamiclights#5]
### Describe the bug

With the new 1.20 pre releases the Torches emit no light when in Hand.
On the Ground they Do.

Also the enchanted shield emits no light.

in 1.19.4 everything is fine

### Steps to reproduce

get 1.20 pre1 and load the datapack

**Comment by WarLord211** [comment]
the renaming fixed it for me.
THX

**Comment by WarLord211** [comment]
Hi with the 1.20 Release Candidate 1
It stopped again working.

Standart version and with the modifikation you mentioned before

**Comment by Tschipcraft** [comment]
That's weird, there is nothing stated in the game changelogs that changed anything significant. I'll have to take a closer look at it

**Comment by Tschipcraft** [comment]
I found a way to not use the `alternative` or `any_of` keyword at all inside the predicates and managed to maintain backwards compatibility down to Minecraft 1.17 with the latest commit. Let me know if you experience any other issues with it 🎉
