### ISSUE TITLE
The Fatal Lag (Guardian Beams)

### ISSUE THREAD

**Issue by Fyoncle** [Tschipcraft/dynamiclights#54]
### Describe the bug

Theres 6 incompatibility as far as i know.
Only incompatibility is not the dynamic lights, but theres also few more.
First group which is unrelated to this lag.
1. Sounds
2. Sound Physics Remastered
3. Make Bubbles Pop (probably unrelated)

And the second group is that.
1. Any Dynamic Light Mod (Causing around 70 fps loss when enabled)
2. Unknown
3. Unknown

How i know theres 2 unknown? well the lag does not happen by 1 mod, but when 2 mods come together it gets created.

My modlist is basically Elysium Days Modpack's 3.2.0 version, but everything else updated to latest, and first suspect group is disabled, which is Sounds and SPR and MBP.

### Steps to reproduce

1. SPECIALLY get into a monument. it doesn't happen in the ground, but only on INSIDE THE naturally GENERATED ocean or monuments.
2. Spawn guardians and anything that guardians attack to, i prefer squids and glow squids.
3. Watch yourself falling into 4 FPS ;D

### Expected behavior

For it to not cause any lag but just work as intended at lights.

**Comment by Tschipcraft** [comment]
First of all, this is a **really** nice looking modpack, respect for that.

I am a bit bothered that the mipmap levels are dropped to 1 because of one item, apparently called medal (should be 16x16 or some power of 2).
```
[17:34:27] [Worker-ResourceReload-4/WARN]:
Texture minecraft:item/medal with size 18x18 limits mip level from 4 to 1
[17:32:01] [Worker-ResourceReload-4/WARN]:
minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 1, because of minimum power of two: 2
```
Low mipmap levels look a lot worse in my opinion (and have a bit of a performance impact), so if you have any idea what mod may be causing this, try to sort it out.

Now that that's out of the way, my guess is that the lag might just be caused by the many glowing ink sack items around the ocean monument from the guardians killing all the glow squids. When I tested for them, there were 124 items. Since they build up over time and take a while to despawn, this could get pretty bad.

![2024-08-31_17 44 40](https://github.com/user-attachments/assets/fa79a469-3a3d-4663-9e67-e44bc3cffcf2)

I could offer to provide a loot table so that glow squids (and regular squids, for fairness?) drop nothing when killed by guardians.
Also lower the bubble lifetime in the settings for Make Bubbles Pop (if not already done in newer modpack versions) to avoid lag from the first group

**Comment by Fyoncle** [comment]
> First of all, this is a **really** nice looking modpack, respect for that.
> 
> I am a bit bothered that the mipmap levels are dropped to 1 because of one item, apparently called medal (should be 16x16 or some power of 2).
> 
> ```
> [17:34:27] [Worker-ResourceReload-4/WARN]:
> Texture minecraft:item/medal with size 18x18 limits mip level from 4 to 1
> [17:32:01] [Worker-ResourceReload-4/WARN]:
> minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 1, because of minimum power of two: 2
> ```
> 
> Low mipmap levels look a lot worse in my opinion (and have a bit of a performance impact), so if you have any idea what mod may be causing this, try to sort it out.
> 
> Now that that's out of the way, my guess is that the lag might just be caused by the many glowing ink sack items around the ocean monument from the guardians killing all the glow squids. When I tested for them, there were 124 items. Since they build up over time and take a while to despawn, this could get pretty bad.
> 
> ![2024-08-31_17 44 40](https://private-user-images.githubusercontent.com/78470530/363424527-fa79a469-3a3d-4663-9e67-e44bc3cffcf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMjEwNTAsIm5iZiI6MTcyNTEyMDc1MCwicGF0aCI6Ii83ODQ3MDUzMC8zNjM0MjQ1MjctZmE3OWE0NjktM2EzZC00NjYzLTllNjctZTQ0YmMzY2ZmY2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDE2MTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwOTE0MjgyMWJiMjc3MzU4NDlhNThiMmJlMDAyODkzZTJmMGJmMzMxNjA3YjEyYmQ1MjFiYjk2Y2YyYjgxNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GMw50Ab23qvkwLRBOgK7ZN3_nHZsco4L8sSVZHfjcUU)
> 
> I could offer to provide a loot table so that glow squids (and regular squids, for fairness?) drop nothing when killed by guardians. Also lower the bubble lifetime in the settings for Make Bubbles Pop (if not already done in newer modpack versions) to avoid lag from the first group

Thank you for your kind words regarding the modpack. I work hard on it ;)

I'll try to sort that mod out, never heard of mipmap things.

And your theory is pretty good, but what about the other 2 mods that killing the FPS which is unknown?

**Comment by Tschipcraft** [comment]
I'm not sure why there should be two unknown mods, you did provide an explanation in the initial report, but I don't understand it lol

[This post from way back in 2013](https://www.minecraftforum.net/forums/minecraft-java-edition/recent-updates-and-snapshots/382231-what-are-mipmap-levels-and-anisotropic-filtering) explains mipmapping pretty well if you're interested

**Comment by Fyoncle** [comment]
> I'm not sure why there should be two unknown mods, you did provide an explanation in the initial report, but I don't understand it lol
> 
> [This post from way back in 2013](https://www.minecraftforum.net/forums/minecraft-java-edition/recent-updates-and-snapshots/382231-what-are-mipmap-levels-and-anisotropic-filtering) explains mipmapping pretty well if you're interested

The FPS without that mod that reducing FPS from guardian beams is actually doesn't reduce it alone, but in need of another mod to work, so that got me thinking, what if theres 2 mods and when they get together that lag happens??

My FPS is around 140 or 150 with guardian beams hitting, but without these "two mods" it being around 250 or 270 so theres definitely something wrong still

**Comment by Fyoncle** [comment]
By the way, turns out, Dynamic Light mods enabling dynamic lights for guardian beams too. Which can be disabled in the config and making FPS back to 150 which is how is it like when Dynamic Light mod disabled, so that issue is solved. but whats causing the rest of the problem?..

**Comment by Tschipcraft** [comment]
So, you're back at using LambDynamicLights, right? What is the rest of the problem, I thought it's working now?

**Comment by Fyoncle** [comment]
> So, you're back at using LambDynamicLights, right? What is the rest of the problem, I thought it's working now?

FPS has to be over 200, but it is around 130, some mods still causing stability issues under water. But since that is probably related to any other cursed mod, this issue can be closed :v

**Comment by Fyoncle** [comment]
Thank you for your helps regarding the lag! It helped ;)

**Comment by Fyoncle** [comment]
I can't reproduce the mip level thingy in the logs, where did you get this from?

**Comment by Tschipcraft** [comment]
Just from the log when launching v3.2.0 of the modpack (unlocked instance with all mods updated). Could be that you removed a mod or resource pack in between updates, and it's not happening anymore. If the warning is not there, you don't need to worry about it

**Comment by Tschipcraft** [comment]
> Thank you for your helps regarding the lag! It helped ;)

Good luck with it!  
PS. You can [change which mobs play a dig up animation](https://github.com/Tschipcraft/spawnanimations/wiki/Exclude-Include-Entities), for example you could add the overhauled creepers or some of the mobs from Deeper and Darker to it

**Comment by Fyoncle** [comment]
> > Thank you for your helps regarding the lag! It helped ;)
> 
> Good luck with it! PS. You can [change which mobs play a dig up animation](https://github.com/Tschipcraft/spawnanimations/wiki/Exclude-Include-Entities), for example you could add the overhauled creepers or some of the mobs from Deeper and Darker to it

Thanks so much! Ill also do that.

**Comment by Fyoncle** [comment]
> Just from the log when launching v3.2.0 of the modpack (unlocked instance with all mods updated). Could be that you removed a mod or resource pack in between updates, and it's not happening anymore. If the warning is not there, you don't need to worry about it

I see now, interesting that theres no item called medal... This will take a valuable time to fix

**Comment by Fyoncle** [comment]
> Just from the log when launching v3.2.0 of the modpack (unlocked instance with all mods updated). Could be that you removed a mod or resource pack in between updates, and it's not happening anymore. If the warning is not there, you don't need to worry about it

Mod called [Hero Proof](https://modrinth.com/mod/hero-proof) is the reason of the mip level issue.

**Comment by Fyoncle** [comment]
> > Thank you for your helps regarding the lag! It helped ;)
> 
> Good luck with it! PS. You can [change which mobs play a dig up animation](https://github.com/Tschipcraft/spawnanimations/wiki/Exclude-Include-Entities), for example you could add the overhauled creepers or some of the mobs from Deeper and Darker to it

Instead of unzipping stuff and sharing that, and repeating this every update is not smart, so i think ill add this compatibility to my mod so it adds them automatically for every version of spawn animations!

**Comment by Tschipcraft** [comment]
Sounds good, sorry that this is a bit hard to configure 😅
