### ISSUE TITLE
Toggle for dynamic lights

### ISSUE THREAD

**Issue by Madis0** [Tschipcraft/dynamiclights#56]
### Is your feature request related to a problem? Please describe.

When installing this as a mod, it appears instantly on all owned worlds. There is currently no way to fully disable it per world nor globally.

### Describe the feature you'd like

A toggle that can be adjusted globally and per-world.

### Describe alternatives you've considered

More toggles per type, e.g. "all items" and "all entities".

### Additional context

I'm aware that there is more granularity when installing it as a datapack, but the concept of installing mods is easier for most users and feasible for modpacks. That said, it could even be useful in datapack form, so that owners can temporarily disable it without having to restart the server (similar to gamerules).

**Comment by KohlrabitoDev** [comment]
To add to this, I'd like a per-player toggle as well, the mod kinda destroys any shader pack built in dynamic lighting. Being able to toggle the mod per player would be really useful, I don't think it needs a permission realistically either.

**Comment by yeetlmao1** [comment]
this doesnt work for me or i dont know how to enable it what do i do to turn this on, 1.21

**Comment by Tschipcraft** [comment]
Thank you for the feature request, toggles per type would be a bit cumbersome to implement with the current setup, but there's nothing in the way for a global toggle. This will be in the next release for Dynamic Lights.

A per-player toggle has already been mentioned in #37 and is also planned.

**Comment by Barujin** [comment]
I just want to be able to disable held items since the jerking around of light while carrying a torch in a cave gets annoying. My shader is just more pleasant.
