### ISSUE TITLE
dosnt work with torch in hand in 1.20 💀

### ISSUE THREAD

**Issue by Eclipse-5214** [Tschipcraft/dynamiclights#6]
### Describe the bug

no dynamic lights apper when torch is in hand
dropped torches work
everything else is fine

### Steps to reproduce

run in 1.20

### Expected behavior

torch would light up surondings

**Comment by Eclipse-5214** [comment]
nvmind dupe issue

**Comment by Tschipcraft** [comment]
The skull emoji at the end lol
