### ISSUE TITLE
Items with NBTs having a light source

### ISSUE THREAD

**Issue by MrAsgard** [Tschipcraft/dynamiclights#61]
### Describe the bug

Hi, its DarkAsgard124 but im on a new profile, few months ago i have gotten in contact with you about manualy updating the datapack to 1.21 so it could work for my atlas realm map, well im back again, im trying to use the datapack for 1.21.3, everything works but items with custom NBTs are emitting light source, can you guide me how to fix it manualy so i could push the updated version of the map to the atlas, thank you very much.

### Steps to reproduce

no NBT ![image](https://github.com/user-attachments/assets/b34593f6-a228-47db-8e06-d19ceb9c389a)
no NBT!![image](https://github.com/user-attachments/assets/41dda13f-447a-4b21-95fc-c776e210d44b)
with NBT ![image](https://github.com/user-attachments/assets/ba1f28cc-4c8f-421d-b83a-de31c3ebac78)
with NBT ![image](https://github.com/user-attachments/assets/2bf9d5c8-fc87-4536-aad8-9f2c5a06021b)

**Comment by Tschipcraft** [comment]
What? I didn't think there would be any major issues when upgrading to 1.21.3. Could you add what NBT you used for the pickaxe?

**Comment by MrAsgard** [comment]
> What? I didn't think there would be any major issues when upgrading to 1.21.3. Could you add what NBT you used for the pickaxe? (ps. nice to see you back at it again)

Okay now i feel kinda dumb.. totally forgot that pickaxe had hidden enchantment which emitted the light, ive disabled it in settings, sorry for wasting your time.
