### ISSUE TITLE
Mod makes world unplayable

### ISSUE THREAD

**Issue by WildTorchix** [Tschipcraft/dynamiclights#65]
### Describe the bug

When I try to load my world, I get an error message, and it tells me I can only play in 'Safe Mode' (Using vanilla data packs only, non-modded) and when I try to create a new world, it force quits minecraft.

### Steps to reproduce

Install using Forge version 52.0.29 and Minecraft version 1.21.1, attempt to load/create a world. (I am using the forge launcher, unsure if it does the same when installed manually)

**Comment by Tschipcraft** [comment]
Thanks for reporting, I will investigate

**Comment by Tschipcraft** [comment]
I was able to trace the problem back to [this pull request](https://github.com/MinecraftForge/MinecraftForge/pull/9955), which changed the forge common tags to use the `c` namespace instead. Referencing the old `forge` tags will now cause the game to crash.
This will be fixed in the next release
