### ISSUE TITLE
Sculk sensors get triggert when the light gets removed

### ISSUE THREAD

**Issue by NilsLehrfeld** [Tschipcraft/dynamiclights#8]
### Describe the bug

When sneaking near a sculk sensor, while holding an item, that creates dynamic light in your main or off-hand, when the invisible marker entity gets removed with the /kill command, it sends out a vibration that triggers said sculk sensors in the area.

### Steps to reproduce

Put a torch, lantern, etc. in your main or off-hand.
Position yourself near a sculk sensor, that detects you running around for example.
Start sneak walking near the sculk sensor.

### Expected behavior

The sculk sensor should not detect the player when holding something that emmits light while sneaking.

### Additional context

I wrote a quick fix that came to my mind while writing this bug report. By just teleporting the marker away before killing it no vibrations will trigger the sculk sensors near the player. I don't know if this is ideal or not. I am not very experienced when it comes to this stuff.
From the "remove_light.mcfunction" I moved the last line into a new function "kill_marker.mcfunction"
Then I added two new lines to the "remove_light.mcfunction"
**execute as @s[type=minecraft:marker,tag=ts.dl.light] at @s run tp @s ~ 320 ~
function dynamiclights:internal/kill_marker**

And at last I want to thank you for creating this awesome datapack.

[mcfunction files.zip](https://github.com/Tschipcraft/dynamiclights/files/12324565/mcfunction.files.zip)

**Comment by Tschipcraft** [comment]
Thank you for bringing this to my attention. Never thought that killing a marker entity, that the client can't even see, triggers sculk sensors...
The provided solution is ideal 👍
